### ISSUE TITLE
Benchmarking Issue

### ISSUE THREAD

**Issue by furkanturan** [durellinux/ZedBoard_Linux_DMA_driver#4]
I have tested your example today. It really works as a DMA driver, but I think there is an issue with your benchmarking results.

I think there needs a clearance to be made. While testing copy speed of ARM, you copy with a for loop, not with memcpy. If you use memcpy you will make it faster and reach to better copying bandwidth that you will not be able to beat with DMA because your `ds_axidma_write()` and `ds_axidma_read()` already performs same memcpy operation.

Am I thinking wrong?

**Comment by durellinux** [comment]
You are right regarding the fact that memcpy would have been faster for the reason you mention.
It is a evaluation we can add to better characterize the core.

However the results with the for loop are the one we are interested in, we were not interested in building a DMA to copy data from main memory to main memory, but we wanted to transfer data to HW cores in the PL.
The test analyze the performance of data transfer with no computation involved which corresponds to a for loop in SW.
When computation is involved you will add the code inside the for loop for the SW side and chain HW cores to the DMA in HW, so we believe that the tests performed are correct.

Does this explanation clarify your doubts?

**Comment by furkanturan** [comment]
That is a perfect explanation in my opinion. That you very much for response.
